version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: 'always'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=task-manager
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
